import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { TimelineProvider } from "@/context/TimelineContext";
import { Toaster } from "react-hot-toast";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Keen keeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#e9e9e9]">
        <Navbar/>
         <TimelineProvider>
          {children}
          <Toaster position="top-right" />
        </TimelineProvider>

        <Footer/>

      </body>
    </html>
  );
}
